version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/falah/project/script-c/my-data:/var/lib/mysql
  apps:
    image: apps
    restart: always
    ports:
      - '30000:80'
    volumes:
      - /home/falah/project/script-c/apps:/var/www/html

volumes:
  my-data:
    driver: local

volumes:
  conf:
    driver: local

