version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '33006:3306'
    expose:
      - '3306'
    volumes:
      - $PWD/my-data:/var/lib/mysql
  apps:
    image: falahalaf/php8
    restart: always
    ports:
      - '30000:80'
    volumes:
      - $PWD/apps:/var/www/html

